
image: bitbucketpipelines/android-ci-image

pipelines:
  branches:
    master:
        - step:
            name: Deploy To Firbase App Distribution
            caches:
              - gradle
            script:
              - . ./android/deploy_to_firebase_app_distribution.sh
            artifacts:
              - app/build/outputs/**