
image: node:10.15.3

pipelines:
 branches:
   master:
       - step:
           image: node:10.15.3
           caches:
             - node
             - gradle
           script: # Modify the commands below to build your repository.
            #env preperation
             - npm install
       - step:
           name: Deploy To Firebase App Distribution
           image: mingc/android-build-box:latest
           caches:
             - node
           script:
             - export FIREBASE_TOKEN=$FIREBASE_REFRESH_TOKEN             
             - cd ./android
             - chmod +x gradlew
               # Needed for env variable changes
             - ./gradlew --stop

               # Build and deploy apk to Firebase App Distribution
             - ./gradlew assembleRelease appDistributionUploadRelease
           artifacts:
             - app/build/outputs/**